In [2]:
#  Zadanie A
import matplotlib.pyplot as plt
import numpy as np
import math

plin = 0.2
plout = 0.5
nplin = 0.8
nplout = 0.5

n = 1000

start_state = [
    [nplin*nplin, plin*(nplin*2), plin*plin],
    [nplin*nplout, (plin*plout)+(nplin*nplout), plin*plout],
    [nplout*nplout, plout*(nplout*2), plout*plout],
]

results = start_state
res_maxs = []

for i in range(n):
    results = np.dot(results, start_state)
    
print(results)

[[0.51020408 0.40816327 0.08163265]
 [0.51020408 0.40816327 0.08163265]
 [0.51020408 0.40816327 0.08163265]]


In [3]:
# Zadania B

X = 0
Y = 1
Z = 0
logged = 1

for i in range(1000):
    rand_num = np.random.rand()
    
    if rand_num <= start_state[logged][0]:
        logged = 0
        X += 1
    elif rand_num <= (start_state[logged][0] + start_state[logged][1]):
        logged = 1
        Y += 1
    elif rand_num > (start_state[logged][0] + start_state[logged][1]):
        logged = 2
        Z += 1
        
print([X/n, Y/n, Z/n])


[0.501, 0.43, 0.07]


In [1]:
# Zadanie C

start = [1 for i in range(100)]

results = [ start, ]

for i in range(10000):
    states = results[-1]
    for i in states:
        rand = np.random.random_sample()
        if i == 0:
            i = 1 if rand <= (plin*nplin) else 0
        if i == 1:
            i = 0 if rand <= (plout*nplout) else 1
    
    results.append(states)
    

print(results)

plt.plot(range(10001), [sum(i)/len(i) for i in results])
plt.show()

NameError: name 'np' is not defined